GET https://cse341-01-z2a3.onrender.com

###

GET https://cse341-01-z2a3.onrender.com/helaman


###
GET https://localhost:3000/contacts
###
GET https://cse341-01-z2a3.onrender.com/contacts
###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}